# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Rack::Handler::WEBrick; end
module Button::MercadoPago; end
module IPN::MercadoPago; end
module Mercadopago::HttpClient::RestClient::Exception; end
module Mercadopago::HttpClient::RestClient::Request; end
