name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruby:3.4

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: Cache gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: |
        bundle config set --local path vendor/bundle
        bundle install

    - name: Rubocop
      run: rubocop lib

    - name: Run tests
      run: bundle exec rake
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_V2 }}
