name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test on Ruby ${{ matrix.ruby-version }}
    runs-on: ubuntu-latest
    container: ruby:${{ matrix.ruby-version }}

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.2", "3.3", "3.4"]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Install dependencies
        run: bundle install

      - name: Lint with Rubocop
        run: bundle exec rubocop lib

      - name: Run unit tests
        run: bundle exec rake test

      - name: Dependency audit
        run: |
          gem install bundler-audit --no-document
          bundle-audit check --update

      - name: Dependency review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v4
        with:
          fail-on-severity: high
