name: Release SDK - Publish Gem

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    container: ruby:3.4

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install dependencies
        run: bundle install

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build gem
        run: gem build *.gemspec

      - name: Publish gem to rubygems.org
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: gem push *.gem

      - name: Wait for release to propagate
        run: gem install rubygems-await
